name: Update fixtures/results (Limerick GAA Hub)

on:
  workflow_dispatch:
  schedule:
    - cron: "15 7,17 * * *"   # 07:15 & 17:15 Europe/Dublin

permissions:
  contents: write

concurrency:
  group: limerickgaahub-data-update
  cancel-in-progress: true

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scripts/scrape_limerickgaa.py

      - name: Commit data changes
        run: |
          if [[ -n "$(git status --porcelain data)" ]]; then
            git config user.name  "gha-bot"
            git config user.email "gha-bot@example.com"
            git fetch origin main
            git pull --rebase origin main
            git add data/*.json
            git commit -m "Auto-update fixtures/results"
            git push
          else
            echo "No changes to commit."
          fi
