name: Update Limerick GAA Fixtures

on:
  schedule:
    # Runs every day at 07:15 UTC and 19:15 UTC
    - cron: '15 7,19 * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: |
          python scripts/scrape_fixtures.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/hurling_2025.json
          git commit -m "Auto-update fixtures" || echo "No changes to commit"
          git push
